spring:

  security:
    user:
      name: ${username}
      password: ${password}

  data:
    mongodb:
      uri: ${Database_Con}
      database: fitRoute
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: ${file_size}
      max-request-size: ${request_size}

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: ${swagger_path}

firebase:
  credentials:
    "type": ${credentials_type}
    project_id: ${credentials_project_id}
    private_key_id: ${credentials_private_key_id}
    private_key: ${credentials_private_key_id}
    client_email: ${credentials_private_key}
    client_id: ${credentials_private_key_id}
    auth_uri: ${credentials_client_id}
    token_uri: ${credentials_token_uri}
    auth_provider_x509_cert_url: ${credentials_auth_provider_x509_cert_url}
    client_x509_cert_url: ${credentials_client_x509_cert_url}
    universe_domain: ${credentials_client_x509_cert_url}

Cloudinary:
  cloud_name: ${cloudinary_cloud_name}
  api_key: ${cloudinary_api_key}
  api_secret: ${cloudinary_api_secret}

jwt:
  secret: ${JWT_key}
  login-validity: ${JWT_Login_Validity}
