spring:

  security:
    user:
      name: ${username}
      password: ${password}

  data:
    mongodb:
      uri: ${Database_Con}
      database: fitRoute
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      max-file-size: ${file_size}
      max-request-size: ${request_size}

  mail:
    host: ${mail_host}
    port: ${mail_port}
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: ${swagger_path}

firebase:
  credentials: ${firebase_credentials}

Cloudinary:
  cloud_name: ${cloudinary_cloud_name}
  api_key: ${cloudinary_api_key}
  api_secret: ${cloudinary_api_secret}

jwt:
  secret: ${JWT_key}

google:
  clientId: ${google_clientId}