spring:
  security:
    user:
      name: ${ login_username }
      password: ${ login_password }

  data:
    mongodb:
      uri: ${Database-Con}
      database: fitRoute
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: ${ swagger_path }

firebase-base-url: ${ firebase_image_url }
jwt-secret: ${ JWT_key }